spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/receitas
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

server.port=8080