spring.application.name=api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/receitas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



jwt.public.key=${JWT_PUBLIC_KEY:classpath:app.pub}
jwt.private.key=${JWT_PRIVATE_KEY:classpath:app.key}

server.port=8080
