version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: receitas-db
    restart: unless-stopped

    
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: receitas
    ports:
      - "5432:5432"
    volumes:
      - receitas_data:/var/lib/postgresql/data

volumes:
  receitas_data:
